### ISSUE TITLE
Compute Mahalanobis distance for observed exogenous variables

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#12]
# To-Do:

# Done:
- [X] Allow `mahalanobis_exo` to handle missing data (e.g., use `norm2::emNorm` and `modi::MDmiss`). (0408384ce7af16f027ae5bc9dadc576ea1485067)
- [X] Update `mahalanobis_exo` to detect a model without exogenous observed variables. (1377cbb7596544fec85074da7c5e519f6cf0174f) 
- [X] Write a test to test whether `mahalanobis_exo` can detect unsupported models. (e2e37f943bd5571a706eafaacd757dfcf8ebbba7)
- [x] Update `mahalanobis_exo` to be able to accept a `lavaan_rerun` object. (f12fb81acb6fb552387b9fdc138d24d9dd5b9135)
- [x] Find a reliable way to identify exogenous observed variables. An observed variable is considered exogenous if it is not influenced by any other variables, even if `fixed.x = FALSE` and so it is considered random. (088d6b75f44b73048355dbe0bdbce1940a7eeddd)
- [x] Draft a test for this function. (088d6b75f44b73048355dbe0bdbce1940a7eeddd)
- [x] Draft this function. (088d6b75f44b73048355dbe0bdbce1940a7eeddd)

# Note:
- One possible way to identify exogenous observed variables: Use `lavInspect(fit, "free")` and check the `beta` matrix. If the row of a variable has only `0s`, then it is exogenous. Checked for a path model. Need to check a CFA model.
