### ISSUE TITLE
Finalize the first release

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#18]
Just an issue to mark the end of the milestone "first release for public testing" (https://github.com/sfcheung/semfindr/milestone/1).

# To-Do
- [x] Proofread all help pages
- [x] Proofread all vignettes
- [x] Run devtools::check()
- [x] Push to main (1f0762e6492cd3388fbbbf80f9b5b225a9e0b937)
