### ISSUE TITLE
Check the documentations of all functions

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#19]
# To-Do

- [x] semfindr-package: Check.
- [x] data: Check
- [x] influence_plot: Fix any typos and add at least one example for each function.
- [x] mahalanobis_rerun: Fix any typos and add at least one example for each function.
- [x] print_lavaan_rerun: Fix any typos and add at least one example for each function.
- [x] Add author
- [x] mahalanobis_exo: Fix any typos and add at least one example for each function.
