### ISSUE TITLE
Update `lavaan_rerun` to decide the cases to rerun based on some criteria

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#21]
# To-Do:

- [x] Users can set the number of cases with the highest residuals computed from the implied endogenous variable scores.
  - Need to write a helper function to compute the implied residuals. Users only specify the number of cases to rerun.
  - [x] Write a test first. (fcec9a84dd667a508bff2abbbc5df27dd82447e6)
  - [x] Revise `lavaan_rerun` to select *u* cases with largest distance to process. (fcec9a84dd667a508bff2abbbc5df27dd82447e6)
- [x] Users can specify the cases to rerun by row numbers in the lavaan stored dataset (ad4a1941a10b52645b4b8cda0ba6955ebd13e16b)
  - Users can specify cases either by row names or by case_ids if `case_id` is specified.

- [x] Users can set the number of cases with the highest Mahalanobis distance based on all variables used in the model.
  - Can let `lavaan_rerun` compute the distances internally. Users only specify the number of cases to rerun.
  - [x] Write a test first. (2f763464934d5b57385f984b64719c8e3be426f8)
  - [x] Revise `mahalanobis_rerun` to allow for missing data and can process a matrix of numbers as input. (2f763464934d5b57385f984b64719c8e3be426f8)
  - [x] Revise `lavaan_rerun` to call this function to compute the Mahalanobis distance for all cases, and only select *u* cases with largest distance to process. (2e22c57fc470364a6ca15bdeb8ce4c73e62813ca)
