### ISSUE TITLE
`mahalanobis_rerun` cannot handle `lavaan_rerun` objects that only have selected case reran

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#22]
# To-Do
- [x] Check all other functions that process a `lavaan_rerun` object to see if they have this problem too.
- [x] Revise `mahalanobis_rerun` to use this vector to extract Mahalanobis distances computed on the full sample. (750ec8bcc3412f5b99cc8d8f215c5ae0fd3db693)
- [x] Revise `lavaan_rerun` to store the row numbers (`case.idx` in `lavaan`) of cases removed in the reruns. (3d2031d7a16b6863b822b2ace1c0032086dcca2b)
