### ISSUE TITLE
More vignettes

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#23]
# To-Do
- [x] Proofread the vignettes
- [x] Draft a guide on selecting cases to delete in `lavaan_rerun`. (095adcb8d08658766bd04477be1aa520f876ba42)
- [x] Draft a guide on using user-supplied case ID. (79b05d252e81acfcc1402f6e68cd1423037463a8)
