### ISSUE TITLE
Allow users to run `lavaan_rerun` on a fit object with inadmissible solution

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#26]
# To-Dos
- [x] Revise `lavaan_rerun` such that it allow users to rerun a fit object that did not converge or the results are not admissible. (cdf5453249a9e82a25f5a99a1adb2cb60e95c38f)
- [x] Write a test. (b932604e9b9b8ca5d851695d8687e61950ce5cea)
- [x] Create a data set and model that convergence is achieved but the solution is not admissible. (b932604e9b9b8ca5d851695d8687e61950ce5cea, 755063c401ade57aeb10eabc35bec56e37f2f96a)
