### ISSUE TITLE
Add a few more sample datasets

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#3]
# To-Do: 
- [x] A path model with potential influential cases. (d184fdd1203cc009872f7d594d17971410303504)
- [x] A CFA model with potential influential cases. (d184fdd1203cc009872f7d594d17971410303504)
- [x] An SEM model with potential influential cases. (d184fdd1203cc009872f7d594d17971410303504)

Note: Move it to a higher priority because they can be used to test other functions to be written.
