### ISSUE TITLE
For functions that allow users to select parameters (e.g., `est_change()`), allow users to select by operators

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#32]
# To-Do
- [x] Write tests for this feature.
- [x] Revise the functions to let users select parameters by supplying a vector of operators, e.g,. `c("=~")`.
  - [x] `est_change()`
  - [x] `est_change_raw()`
  - [X] `influence_stat()`: No need to change it. It pass `parameters` directly to `est_change()`. Let `est_change()` handle the change.
- [x] List functions that allow users to select parameters.
