### ISSUE TITLE
Add and update the vignettes

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#34]
# Status

- No need for now. The help pages of most main functions already have examples for these models.

# To-Do

- [ ] Using a CFA model
- [ ] Using a path model
- [ ] Using a SEM model

# Note

Already have sample datasets for CFA and SEM models.
