### ISSUE TITLE
Add support for multi-sample models

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#35]
# To-Do
- [x] Revise `lavaan_rerun()` to support multiple-group models.
- [x] Revise `est_change()` to support multiple-group models.
- [x] Revise `est_change_raw()` to support multiple-group models.
- [x] Revise `fit_measures()` to support multiple-group models.
- [x] Revise `mahalanobis_rerun()` to support multiple-group models.
- [x] Revise `mahalanobis_predictors()` to support multiple-group models.
- [x] Revise `influence_stat()` to support multiple-group models.
- [x] Revise `fit_measures_approx()` to support multiple-group models.
- [x] Revise `est_change_approx()` to support multiple-group models.
- [x] Revise `est_change_raw_approx()` to support multiple-group models.
- [x]  Revise `implied_scores()` to support multiple-group models.
- [x] Revise `influence_stat()` to support multiple-group models.
- [x] Update parameter selection for multiple-group models. <- Already supported
- [x] Update all documentation.

# Status

Working on the branch `multi_sample`.

# Note

For a multi-sample models, `lavaan` stores the data as (1) a list of matrix, and (2) a list of `case.idx` matching the cases to the original dataset.

Possible approach:
- Reconstruct the full dataset from the list of matrix and the list of `case.idx`.
- In `gen_fct_use_lavaan`, reconstruct the full dataset and proceed as usual using case index in the full sample.
- In `lavaan_rerun`, only lines on case ids need to be revised.

Most other functions should work fine whether the model is multi-sample or not.

Mahalanobis distance is computed using within-group means and covariance matrices.

**Comment by sfcheung** [comment]
#78
