### ISSUE TITLE
Use row number in parameter table to identify parameters

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#36]
# Note

This approach is more reliable than matching parameter specifications.
This will also make it easier to support multiple-group models.

# Status

Working on this branch: [parameterid](https://github.com/sfcheung/semfindr/tree/parameterid).

# To-Do

- [x] Revise functions that compute stats for parameters to use parameter table row numbers.
  - [x] `est_change()`
  - [x] `est_change_raw()`
  - [x] `est_change_approx()`
  - [x] `est_change_raw_approx()`
- [x] Factor out the part to get est changes, and add wrappers to handle extraction of parameters.
- [x] Write a function to convert the ids generated above to `lhs`, `op`, `rhs`, and `group` columns. <- `pars_id_to_lorg()`
- [x] Write a function to convert lavaan syntax to positions in the parameter vector (output of `coef()` or `parameterTable()`). No need for the output of `parameterEstimates()` because the rows included are not fixed but depends on some arguments.
- [x] ~~Write a function to convert positions back to parameter specifications (e.g., "x ~ y")~~ <- May not be necessary because they are just names in the output of `coef()`. <- Not necessary. Can use `lavaan::lav_partable_labels()`.
