### ISSUE TITLE
Revise `lavaan_rerun()` to note down reruns that failed to converge

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#44]
# To-Dos

- [x] Write a test for cases with failures to converge. (ee63358a94a37d1c5066b577f43a307e830cc57e)
- [x] Revise `lavaan_reurn()` to note down cases failed to converge. (d464f6764e695f1c1e4f3029416d296ea5bfdfd4)
- [x] Test `lavaan_rerun()`. (d464f6764e695f1c1e4f3029416d296ea5bfdfd4)
- [x] Update functions that will use `post.check` in processing the reruns to use `converged` too:
    - [x] `est_change_raw()` (9da8b79fef85d2dd8c099ccd04ffaa385d7cd456)
    - [x] `est_change()` (9da8b79fef85d2dd8c099ccd04ffaa385d7cd456)
    - [x] `fit_measures_change()` (9da8b79fef85d2dd8c099ccd04ffaa385d7cd456)
    - [x] `print.lavaan_rerun()` <- Do this in #27
