### ISSUE TITLE
Final checks before pushing to version 0.1.1

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#45]
# To-Do

- [x] Check the documentation of new functions.
- [x] Check the documentation of old functions.
- [x] Check the documentation of functions: Are all classes documented?
- [x] Proofread the examples.
- [x] Proofread the vignettes.
  - [x] `semfindr.Rmd`
  - [x] `casewise_scores.Rmd`
  - [x] `selecting_cases.Rmd`
  - [x] `user_id.Rmd`
- [x] Update NEWS.
- [x] Update DESCRIPTION.
- [x] Test by `testthat`.
- [x] Check by `pkgdown::build_site()`
- [x] Check by `devtools::check()`.

# Status

Doing this on the branch `final_check_45` based on `devel`.
