### ISSUE TITLE
Write a print method for the output of each main function

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#76]
# Done

Versions 0.1.4.3 to 0.1.4.7.

# To-Dos
- [x] Write a print method for the output of `est_change_raw()`.
- [x] Write a print method for the output of `est_change_raw_approx()`.
- [x] Write a print method for the output of `est_change()`.
- [x] Write a print method for the output of `est_change_approx()`.
- [x] Write a print method for the output of `fit_measures_change()`.
- [x] Write a print method for the output of `fit_measures_change_approx()`.
- [x] Write a print method for the output of `mahalanobis_predictors()`.
- [x] Write a print method for the output of `mahalanobis_rerun()`.
- [x] Write a print method for the output of `influence_stat()`.

# Note

Users not familiar with matrices and data frame may find it inconvenient to read the results.

**Comment by sfcheung** [comment]
Done in #77
