### ISSUE TITLE
Case influence on a function of model parameters

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semfindr#93]
# To-Dos

- [x] Write a test.
- [x] Write the function: `user_change_raw()`.
- [x] Allow additional arguments for `user_function`.
- [x] Write the example.
- [x] Revise a few other functions to work for it.
    - [x] print for est_change
    - [x] index_pl;ot: No need to revise

# Status

Working on the branch `user_function`.

# Note

In addition to model parameters, allow users to supply a function that receives a fit object and return something, like what `bootstrapLavaan()` does?

Write `any_change()`?

**Comment by sfcheung** [comment]
Closed. Done in #105
